<?php

/**
 * Question/Answer array of all the sections
 * @author Amit Sahu 
 */
$behaviours =array(
				1=> array ( "title" => "Getting Results", 			"type" => "D"),
				2=> array ( "title" => "Contacting people", 		"type" => "I"),
				3=> array ( "title" => "Being patient", 			"type" => "S"),
				4=> array ( "title" => "Following directions", 		"type" => "C"),
				5=> array ( "title" => "Impressing others", 		"type" => "D"),
				6=> array ( "title" => "Special skills", 			"type" => "C"),
				7=> array ( "title" => "Challenging others", 		"type" => "I"),
				8=> array ( "title" => "Controlling quality", 		"type" => "C"),
				9=> array ( "title" => "Concentrating on work", 	"type" => "D"),
				10=> array ( "title" => "Action orientated",		"type" => "D"),
				11=> array ( "title" => "Concentrating on detail", 	"type" => "I"),
				12=> array ( "title" => "Communicates easily", 		"type" => "S"),
				13=> array ( "title" => "Controlling circumstances","type" => "I"),
				14=> array ( "title" => "Satisfied with job level", "type" => "S"),
				15=> array ( "title" => "Motivating people", 		"type" => "C"),
				16=> array ( "title" => "Venturing the unknown", 	"type" => "D"),
				17=> array ( "title" => "Enforcing decisions", 		"type" => "I"),
				18=> array ( "title" => "Desire to help", 			"type" => "C"),
				19=> array ( "title" => "Being diplomatic",			"type" => "C"),
				20=> array ( "title" => "Very loyal to job", 		"type" => "S"),
				21=> array ( "title" => "Being enthusiastic", 		"type" => "I"),
				22=> array ( "title" => "Checking accuracy",		"type" => "D"),
				23=> array ( "title" => "Taking Authority", 		"type" => "C"),
				24=> array ( "title" => "Composed individual", 		"type" => "I"),
				25=> array ( "title" => "Listen intently", 			"type" => "S"),
				26=> array ( "title" => "Complying with rules", 	"type" => "C"),
				27=> array ( "title" => "Solving problems", 		"type" => "D"),
				28=> array ( "title" => "Entertaining people", 		"type" => "I"),
				29=> array ( "title" => "Adhering to procedure", 	"type" => "S"),
				30=> array ( "title" => "Good listener", 			"type" => "C"),
				31=> array ( "title" => "Radiating optimism", 		"type" => "I"),
				32=> array ( "title" => "Goal driven", 				"type" => "D"),
				33=> array ( "title" => "Outgoing attitude", 		"type" => "C"),
				34=> array ( "title" => "Take responsibility", 		"type" => "S"),
				35=> array ( "title" => "Likes predictability", 	"type" => "C"),
				36=> array ( "title" => "Avoiding trouble", 		"type" => "D"),
				37=> array ( "title" => "Challenging tasks", 		"type" => "S"),
				38=> array ( "title" => "Very thorough", 			"type" => "I"),
				39=> array ( "title" => "Connect with people", 		"type" => "D"),
				40=> array ( "title" => "Likes repetitive work", 	"type" => "S"),
				41=> array ( "title" => "Careful planning", 		"type" => "I"),
				42=> array ( "title" => "Being positive", 			"type" => "S"),
				43=> array ( "title" => "Calm under pressure", 		"type" => "S"),
				44=> array ( "title" => "Likes competing", 			"type" => "D"),
				45=> array ( "title" => "Comfortable with systems", "type" => "S"),
				46=> array ( "title" => "Say it as it is", 			"type" => "I"),
				47=> array ( "title" => "Analysing risks", 			"type" => "C"),
				48=> array ( "title" => "Likes persuading", 		"type" => "C"),
				49=> array ( "title" => "Technical competence", 	"type" => "S"),
				50=> array ( "title" => "Public recognition", 		"type" => "D"),
				51=> array ( "title" => "Always want to win", 		"type" => "C"),
				52=> array ( "title" => "Respects tradition", 		"type" => "I"),
				53=> array ( "title" => "Direct answers", 			"type" => "D"),
				54=> array ( "title" => "Wants security", 			"type" => "I"),
				55=> array ( "title" => "Freedom of speech", 		"type" => "S"),
				56=> array ( "title" => "Quick to notice mistakes", "type" => "D"),
				57=> array ( "title" => "Structured presentation", 	"type" => "S"),
				58=> array ( "title" => "New activities", 			"type" => "I"),
				59=> array ( "title" => "Following rules", 			"type" => "C"),
				60=> array ( "title" => "Democracy", 				"type" => "C"),
				61=> array ( "title" => "Personal attention", 		"type" => "D"),
				62=> array ( "title" => "Not too much change", 		"type" => "C"),
				63=> array ( "title" => "Detailed explanations", 	"type" => "I"),
				64=> array ( "title" => "Want to be in control", 	"type" => "D"),
				65=> array ( "title" => "Free from supervision", 	"type" => "S"),
				66=> array ( "title" => "Group activities", 		"type" => "S"),
				67=> array ( "title" => "Sincere", 				    "type" => "I"),
				68=> array ( "title" => "Precision work", 			"type" => "D"),
				69=> array ( "title" => "Enjoy planning", 			"type" => "C"),
				70=> array ( "title" => "Detailed information", 	"type" => "S"),
				71=> array ( "title" => "Likes fashion", 			"type" => "D"),
				72=> array ( "title" => "Likes Prestige", 			"type" => "I"),
				73=> array ( "title" => "Favourable impressions", 	"type" => "S"),
				74=> array ( "title" => "Ask how then what", 		"type" => "C"),
				75=> array ( "title" => "Ask what then how", 		"type" => "I"),
				76=> array ( "title" => "Working from one place", 	"type" => "D"),
				77=> array ( "title" => "Needs security", 			"type" => "C"),
				78=> array ( "title" => "Questioning Status quo", 	"type" => "D"),
				79=> array ( "title" => "Wants status quo", 		"type" => "S"),
				80=> array ( "title" => "Needs people", 			"type" => "I"),
				81=> array ( "title" => "Very sincere", 			"type" => "C-"),
				82=> array ( "title" => "Seek facts", 				"type" => "C-"),
				83=> array ( "title" => "Seek variety", 			"type" => "S-"),
				84=> array ( "title" => "Challenge the rule", 		"type" => "I-"),
				85=> array ( "title" => "Self-willed", 				"type" => "S-"),
				86=> array ( "title" => "Considerate of others", 	"type" => "I-"),
				87=> array ( "title" => "Seen as blunt", 			"type" => "D-"),
				88=> array ( "title" => "Reacts quickly to change", "type" => "I-"),
				89=> array ( "title" => "Wide scope of interests", 	"type" => "S-"),
				90=> array ( "title" => "Seen as stubborn", 		"type" => "D-"),
				91=> array ( "title" => "Need time to make decisions",		"type" => "I-"),
				92=> array ( "title" => "Like to work alone", 				"type" => "D-"),
				93=> array ( "title" => "Unconcerned with details", 		"type" => "C-"),
				94=> array ( "title" => "Likes to demonstrate ideas", 		"type" => "S-"),
				95=> array ( "title" => "Things above people", 				"type" => "C-"),
				96=> array ( "title" => "Likes long term planning", 		"type" => "D-"),
				97=> array ( "title" => "Reflect on new ideas", 			"type" => "C-"),
				98=> array ( "title" => "Have strong opinions", 			"type" => "I-"),
				99=> array ( "title" => "Wants limited responsibilities", 	"type" => "D-"),
				100=> array ( "title" => "Seen as opportunistic", 			"type" => "S-"),
				101=> array ( "title" => "Seeks unpredictable environments","type" => "S-"),
				102=> array ( "title" => "Tries to avoid competition", 		 "type" => "I-"),
				103=> array ( "title" => "Unsystematic approach", 			 "type" => "D-"),
				104=> array ( "title" => "Think about things logically", 	 "type" => "I-"),
				105=> array ( "title" => "More analytical thinker", 		 "type" => "D-"),
				106=> array ( "title" => "Will consider alternatives", 		 "type" => "C-"),
				107=> array ( "title" => "Very receptive to change", 		 "type" => "S-"),
				108=> array ( "title" => "Prefer low risk decisions", 		 "type" => "C-"),
				109=> array ( "title" => "Dislikes conflict", 				 "type" => "I-"),
				110=> array ( "title" => "Likes researching things", 		 "type" => "C-"),
				111=> array ( "title" => "Open-minded", 				     "type" => "C-"),
				112=> array ( "title" => "Having a sens of urgency", 		 "type" => "S-"),
				113=> array ( "title" => "Likes mobility", 				     "type" => "I-"),
				114=> array ( "title" => "Quality above quantity", 			 "type" => "D-"),
				115=> array ( "title" => "Prefers independence", 			 "type" => "S-"),
				116=> array ( "title" => "Less cautious", 				     "type" => "I-"),
				117=> array ( "title" => "Prefer less social exposure", 	 "type" => "D-"),
				118=> array ( "title" => "Unlimited territory", 			 "type" => "S-"),
				119=> array ( "title" => "Free from rules", 				 "type" => "C-"),
				120=> array ( "title" => "Wants to be seen as very patient", 				 "type" => "D-"),
				
			);
?>