<?php 

$behaviours = array(

				1=> array ( "title" => "I prefer working in an orderly environment", 									"type" => "J"),
				2=> array ( "title" => "I prefer not to change anything on a project once I've started", 	"type" => "J"),
				3=> array ( "title" => "I prefer a more formal work environment than casual", 										"type" => "J"),
				4=> array ( "title" => "I see myself as a perfectionist", 									"type" => "S"),
				5=> array ( "title" => "I like spending time with a large group of friends", 						"type" => "E"),
				6=> array ( "title" => "I mostly prefer to look at the facts than feelings when making decisions", 									"type" => "T"),
				7=> array ( "title" => "I like to socialise a lot", 											"type" => "E"),
				8=> array ( "title" => "I am very firm when dealing with conflict", 											"type" => "T"),
				9=> array ( "title" => "I don't like going to the movies alone", 							"type" => "E"),
				10=> array ( "title" => "I prefer to look for evidence that makes sense when solving problems",						"type" => "S"),
				11=> array ( "title" => "I talk a lot", 													"type" => "E"),
				12=> array ( "title" => "I am more realistic than intuitive", 							"type" => "S"),
				13=> array ( "title" => "I good at recalling past events very accurately",							"type" => "S"),
				14=> array ( "title" => "I openly share my ideas and thoughts",						"type" => "E"),
				15=> array ( "title" => "I only use tangible information when deciding on something", 		"type" => "S"),
				16=> array ( "title" => "I believe it is more important to focus on the job than on the feelings of others", 	"type" => "T"),
				17=> array ( "title" => "I like to make to-do lists at work", 										"type" => "J"),
				18=> array ( "title" => "I see myself as very practical and hands-on", 									"type" => "S"),
				19=> array ( "title" => "I openly tell others what I think",						"type" => "E"),
				20=> array ( "title" => "I prefer a very structured work environment", 												"type" => "J"),
				21=> array ( "title" => "I like explaining things in great detail", 						"type" => "S"),
				22=> array ( "title" => "I'm comfortable making tough decisions",						"type" => "T"),
				23=> array ( "title" => "I like to plan my day", 											"type" => "J"),
				24=> array ( "title" => "I enjoy going out with large groups", 								"type" => "E"),
				25=> array ( "title" => "I prefer to solve problems that has clear outcomes", 				"type" => "S"),
				26=> array ( "title" => "I don't like to think about different theories and random ideas", 					"type" => "S"),
				27=> array ( "title" => "I mostly decide with my head and not my heart", 							"type" => "T"),
				28=> array ( "title" => "I prefer not to trust my gut feeling", 							"type" => "S"),
				29=> array ( "title" => "I mostly prefer an organised lifestyle", 								"type" => "J"),
				30=> array ( "title" => "I like to base my decisions on what worked before", 					"type" => "S"),
				31=> array ( "title" => "My ideas are usually easy to explain", 								"type" => "S"),
				32=> array ( "title" => "I don't like working on tight deadlines", 						"type" => "J"),
				33=> array ( "title" => "I seek logic before feelings", 									"type" => "T"),
				34=> array ( "title" => "I don't care too much about how others might be feeling", 						"type" => "T"),
				35=> array ( "title" => "Making tough decisions is not difficult at all",				 	"type" => "T"),
				36=> array ( "title" => "I'm less empathetic than most people", 											"type" => "T"),
				37=> array ( "title" => "I'll rather be fair than kind", 									"type" => "T"),
				38=> array ( "title" => "I only change my mind if it is really necessary",			 				"type" => "J"),
				39=> array ( "title" => "I don't see myself as very innovative", 							"type" => "S"),
				40=> array ( "title" => "I enjoy work more when I can interact with others", 					"type" => "E"),
				41=> array ( "title" => "I'm not really a peacemaker", 										"type" => "T"),
				42=> array ( "title" => "Being around a lot of people excites me", 							"type" => "E"),
				43=> array ( "title" => "I openly share my feelings", 										"type" => "E"),
				44=> array ( "title" => "I seek out big crowds", 											"type" => "E"),
				45=> array ( "title" => "I tend to interrupt people", 									"type" => "E"),
				46=> array ( "title" => "I don't need peace and harmony at work", 				"type" => "T"),
				47=> array ( "title" => "I'd rather talk about something than sending an email", 			"type" => "E"),
				48=> array ( "title" => "I prefer communicating directly and verbally", 					"type" => "E"),
				49=> array ( "title" => "I usually introduce myself first", 								"type" => "E"),
				50=> array ( "title" => "I don't like working under pressure", 								"type" => "J"),
				51=> array ( "title" => "I enjoy socialising a lot", 										"type" => "E"),
				52=> array ( "title" => "I don't see myself as impulsive", 									"type" => "J"),
				53=> array ( "title" => "I tend not to reflect too long over things", 						"type" => "E"),
				54=> array ( "title" => "I usually finish what I start", 									"type" => "J"),
				55=> array ( "title" => "I'm not very imaginative", 										"type" => "S"),
				56=> array ( "title" => "I'll rather show justice than mercy", 								"type" => "T"),
				57=> array ( "title" => "I'm not always that flexible with my time", 									"type" => "J"),
				58=> array ( "title" => "I think about the project outcomes first, then about those involved", 				"type" => "T"),
				59=> array ( "title" => "I need the facts before making any decisions", 				"type" => "S"),
				60=> array ( "title" => "I like to organise my day", 										"type" => "J"),
				61=> array ( "title" => "I prefer to look at the explainable, rather than the unknown", 			"type" => "S"),
				62=> array ( "title" => "I like to do a lot of different activities", 						"type" => "E"),
				63=> array ( "title" => "I'm not so sensitive to what others might be thinking of me", 							"type" => "T"),
				64=> array ( "title" => "I'm a very detailed person", 									"type" => "S"),
				65=> array ( "title" => "Work is work and play is play", 			"type" => "J"),
				66=> array ( "title" => "I believe my senses above my intuition", 												"type" => "S"),
				67=> array ( "title" => "I don't like working on tight deadlines",				 				"type" => "J"),
				68=> array ( "title" => "I like having a plan in place", 									"type" => "J"),
				69=> array ( "title" => "I always want to be in control of things", 								"type" => "J"),
				70=> array ( "title" => "I usually read the instructions", 									"type" => "J"),
				71=> array ( "title" => "People's feelings is not that important at work",					"type" => "T"),
				72=> array ( "title" => "People's feelings are not always that obvious to me", 				"type" => "T"),
				73=> array ( "title" => "Constantly pleasing others doesn't appeal to me", 							"type" => "T"),
				74=> array ( "title" => "I always finish what I start", 										"type" => "J"),
				75=> array ( "title" => "I'm seen as the more light-hearted one amongst my friends",		"type" => "E"),
				76=> array ( "title" => "I'd rather discuss something than think about it", 				"type" => "E"),
				77=> array ( "title" => "I always look for facts", 											"type" => "S"),
				78=> array ( "title" => "I'm usually quite impersonal", 								"type" => "T"),
				79=> array ( "title" => "I need the facts before making decisions", 						"type" => "S"),
				80=> array ( "title" => "I'll forgive but don't expect me to forget", 						"type" => "T")
				
			);
?>